import unittest


'''
On_OAuth_creation_successful_response_200
On_OAuth_creation_unsuccessful_throws_AuthError
On_Listener_creation_socket_creation_successful
On_Listener_not_created_throws_SocketError
On_start_TCP_connection_listening_on_port
On_TCP_connection_unsuccessful_throws_ConnectionError
invalid_IP
busy_port
'''